### PR TITLE
Update index.html to correct TTL syntax in example

### PR DESCRIPTION
**Pull request by rob-metalinkage**
https://github.com/w3c/dx-connegp/issues/31

### CODE REVIEW

**Review by pchampin — DISMISSED** [review]
I believe that there is a misunderstanding. The changes in this PR do *not* address the faulty Turtle example pointed in #31.

As a matter of fact, the examples modified by this PR is not Turtle, it is a Link HTTP header, and I believe that it is correct (and that the proposed changes make it incorrect).

**Review by YoucTagh — CHANGES_REQUESTED** [review]
I agree with the request of @pchampin.

**Comment by rob-metalinkage** [comment]
Have (hopefully) fixed - making the changes in the right place this time! and extended the PR to separate example into a TTL for validation (this is not incorporated automatically yet - can we do this with respec?

**Review by nicholascar — APPROVED** [review]

**Review by YoucTagh — CHANGES_REQUESTED** [review]
The typo has been fixed. However, the HTML alternative is not reflected:
```
<http://example.org/resource/a>;
          rel="alternate";
          type="text/html"
```
I believe this part:
```
...
<http://example.org/resource/different> .
```

should be changed to:
```
...
<http://example.org/resource/different> ,
[
        dct:format "text/html" ;
] .
```
The same should be reflected in the draft:
```
...
 &lt;http://example.org/resource/different&gt
.
```
should be: 
```
    &lt;http://example.org/resource/different&gt; ,
    [
        dct:format "text/html" ;
    ] .
```

**Comment by rob-metalinkage** [comment]
Thanks @YoucTagh  - you were correct - this was missing from the turtle .  Updated

**Review by larsgsvensson — APPROVED** [review]
The changes now reflect the proposal by @YoucTagh. Thanks for updating.

**Review by YoucTagh — APPROVED** [review]

**Comment by YoucTagh** [comment]
Thanks for the updates @rob-metalinkage.

**Comment by rob-metalinkage** [comment]
As agreed in meeting 9/8/2023

**Pull request merged**
